version: '3'

services:
  animalshelter:
    restart: on-failure
    build: .
    container_name: animalshelter
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/animalshelter?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
        - 8443:8443
    depends_on:
        - mysql_db
  mysql_db:
    restart: always
    container_name: mysql_db
    image: mysql
    environment:
        MYSQL_DATABASE: animalshelter
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: password
    ports:
        - 3306
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
        interval: 45s
        timeout: 10s
        retries: 10

