version: '3'

services:
  animalshelter:
    image: ihofenix/animalshelter:release10
    restart: always
    ports:
        - "8443:8443"
    container_name: animalshelter
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/animalshelter?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
        WAIT_HOSTS: mysql_db:3306
    depends_on:
        - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: on-failure
    ports:
        - "5000:3306"
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    environment:
        MYSQL_DATABASE: animalshelter
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: password
